name: Daily Build and Cleanup

on:
  schedule:
    - cron: '0 2 * * *' # Runs at 2 AM UTC daily
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  packages: write

jobs:
  build_and_cleanup:
    name: Build Docker image and cleanup old ones
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date for tagging
        id: date
        run: echo "IMAGE_DATE=$(date +'%d%m%Y')" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:production-smb
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:production-smb-${{ env.IMAGE_DATE }}

      - name: Cleanup old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ github.event.repository.name }}
          cut-off: '60 days ago UTC'
          account-type: personal # Change to 'org' if this repository is in an organization
          token: ${{ secrets.GITHUB_TOKEN }}
